name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Run Cypress tests
        run: npx cypress run

      - name: Verify Allure Results Directory
        run: ls -al allure-results

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Verify Allure Report Directory
        run: ls -al allure-report

      - name: Push Allure Report to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set up git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Check out the gh-pages branch
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git worktree add gh-pages gh-pages
          cd gh-pages
          # Clear the gh-pages branch content
          rm -rf ./*
          # Copy the Allure report to the gh-pages branch
          cp -R ../allure-report/* .
          # Commit and push the report to the gh-pages branch
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages

      - name: Set up GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report

      - name: Update GitHub Pages URL in Repo Description
        run: |
          curl -X PATCH "https://api.github.com/repos/${{ github.repository }}" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"description": "Allure Report: https://borderForNoone.github.io/cypress-cucumber"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}