name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: E2E on Chrome

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          group: 'UI-Chrome'
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create cucumber-report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cucumber-report
          path: ./cucumber-report
          retention-days: 1

      - name: Screenshots report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Video report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: List contents of downloaded cucumber-report
        if: always()
        run: ls -R ./cucumber-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download cucumber-report
        uses: actions/download-artifact@v4
        with:
          name: cucumber-report
          path: ./cucumber-report

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./cucumber-report