name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        name: E2E on Chrome

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  browser: chrome
                  record: true
                  parallel: true
              env:
                  group: 'UI-Chrome'
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Screenshots report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  if-no-files-found: ignore

            - name: Video report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-videos
                  path: cypress/videos
                  if-no-files-found: ignore 

            - name: Create cucumber-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: cypress-report
                  path: /cypress/report
                  retension-days: 1     
    
    deplot:
        needs: test
        runs-on: ubuntu-latest
        if: always()

        steps:
            - name: Download cucumber report artifact
              if: always()

              steps:
                  - name: Download cucumber report artifact
                    if: always()
                    run: ls -R

                  - name: Display structure of dowloaded files
                    if: always()
                    run: ls -R

                  - name: Deploy report to Github Pages
                    if: always()
                    uses: peaceiris/actions-gh-pages@v2
                    env:
                        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                        PUBLISH_BRANCH: gh-pages
                        PUBLISH_DIR: ./cucumber-report
