name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: E2E on Chrome

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          group: 'UI-Chrome'
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List contents of cucumber-report
        run: ls -R ./cucumber-report

      - name: Create cucumber-report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: ./cucumber-report
          retention-days: 1

      - name: Screenshots report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Video report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download cucumber report artifact
        uses: actions/download-artifact@v3
        with:
          name: cucumber-report
          path: ./cucumber-report

      - name: List contents of downloaded cucumber-report
        if: always()
        run: ls -R ./cucumber-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cucumber-report