name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: E2E on Chrome

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          group: 'UI-Chrome'
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create cucumber-report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cucumber-report
          path: ./cucumber-report
          retention-days: 1

      - name: Screenshots report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Video report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: List contents of downloaded cucumber-report
        if: always()
        run: ls -R ./cucumber-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download cucumber-report
        uses: actions/download-artifact@v4
        with:
          name: cucumber-report
          path: ./cucumber-report

      - name: Ensure index.html exists
        run: |
          if [ ! -f ./cucumber-report/index.html ]; then
            echo "<html><body><h1>No report available</h1></body></html>" > ./cucumber-report/index.html
          fi

      - name: Copy files to gh-pages branch
        run: |
          mkdir -p ./gh-pages
          cp -R ./cucumber-report/* ./gh-pages/
          
      - name: Commit and push to gh-pages
        run: |
          cd ./gh-pages
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git init
          git add .
          git commit -m "Deploy cucumber report"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages

      - name: Print GitHub Pages URL
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          REPO_OWNER=$(dirname $GITHUB_REPOSITORY)
          echo "GitHub Pages URL: https://${REPO_OWNER}.github.io/${REPO_NAME}/"